-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_user_id uuid NOT NULL,
  entity_id uuid NOT NULL,
  entity_type text NOT NULL,
  parent_entity_id uuid,
  parent_entity_type text,
  action text NOT NULL,
  event_name text NOT NULL,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_events_pkey PRIMARY KEY (id),
  CONSTRAINT activity_events_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  content text NOT NULL,
  is_user boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.chat_sessions(id)
);
CREATE TABLE public.chat_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  guest_id uuid,
  title text NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chat_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT chat_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.chat_start_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  suggestion text NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chat_start_conversations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  start_time timestamp with time zone DEFAULT now(),
  end_time timestamp with time zone DEFAULT now(),
  location text,
  type text DEFAULT 'offline'::text CHECK (type = ANY (ARRAY['offline'::text, 'online'::text])),
  category text,
  timezone text,
  logo text,
  thumbnail text,
  link text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  feedback_text text NOT NULL CHECK (length(feedback_text) >= 10 AND length(feedback_text) <= 1000),
  category text DEFAULT 'general'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  reply_at timestamp with time zone,
  reply_text text,
  reply_by uuid,
  CONSTRAINT feedback_pkey PRIMARY KEY (id),
  CONSTRAINT feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT feedback_reply_by_fkey FOREIGN KEY (reply_by) REFERENCES public.users(id)
);
CREATE TABLE public.feedback_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  feedback_id uuid NOT NULL,
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_size bigint NOT NULL CHECK (file_size <= (20 * 1024 * 1024)),
  mime_type text NOT NULL,
  file_type text NOT NULL CHECK (file_type = ANY (ARRAY['image'::text, 'video'::text])),
  uploaded_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT feedback_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT feedback_attachments_feedback_id_fkey FOREIGN KEY (feedback_id) REFERENCES public.feedback(id),
  CONSTRAINT feedback_attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.gpts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  author text NOT NULL,
  website_url text NOT NULL,
  icon_url text,
  category text,
  name text NOT NULL,
  description text NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT gpts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.interview_answers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  result_id uuid,
  question_id uuid NOT NULL,
  user_answer_text text,
  selected_option_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT interview_answers_pkey PRIMARY KEY (id),
  CONSTRAINT interview_answers_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.interview_questions(id),
  CONSTRAINT interview_answers_selected_option_id_fkey FOREIGN KEY (selected_option_id) REFERENCES public.interview_question_options(id),
  CONSTRAINT interview_answers_result_id_fkey FOREIGN KEY (result_id) REFERENCES public.interview_results(id)
);
CREATE TABLE public.interview_assessment_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assessment_id uuid NOT NULL,
  role text NOT NULL,
  status text NOT NULL DEFAULT 'not_started'::text CHECK (status = ANY (ARRAY['not_started'::text, 'in_progress'::text, 'awaiting_ai'::text, 'completed'::text])),
  answered_count integer DEFAULT 0,
  total_questions integer DEFAULT 0,
  progress_percent numeric DEFAULT 0,
  started_at timestamp with time zone,
  submitted_at timestamp with time zone,
  completed_at timestamp with time zone,
  last_activity_at timestamp with time zone,
  ai_status text DEFAULT 'idle'::text CHECK (ai_status = ANY (ARRAY['idle'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  last_ai_error text,
  duration_seconds integer,
  average_seconds_per_question numeric,
  question_timings jsonb,
  cheating_count integer DEFAULT 0,
  cheating_events jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid,
  answers_snapshot jsonb,
  CONSTRAINT interview_assessment_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT interview_assessment_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT interview_assessment_attempts_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.interview_assessments(id)
);
CREATE TABLE public.interview_assessments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  target_role text NOT NULL UNIQUE,
  duration integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT interview_assessments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.interview_question_options (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  question_id uuid NOT NULL,
  option_text text NOT NULL,
  is_correct boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT interview_question_options_pkey PRIMARY KEY (id),
  CONSTRAINT interview_question_options_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.interview_questions(id)
);
CREATE TABLE public.interview_questions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assessment_id uuid,
  text text NOT NULL,
  type text NOT NULL,
  format text NOT NULL,
  required boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT interview_questions_pkey PRIMARY KEY (id),
  CONSTRAINT interview_questions_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.interview_assessments(id)
);
CREATE TABLE public.interview_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assessment_id uuid NOT NULL,
  strengths jsonb,
  weaknesses jsonb,
  development_suggestions jsonb,
  skill_scores jsonb,
  recommended_roles jsonb,
  summary jsonb,
  ai_summary text,
  analysis_model text,
  analysis_completed_at timestamp with time zone,
  insight_locale text,
  insight_version text,
  hr_review_status text DEFAULT 'pending'::text CHECK (hr_review_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  team_fit uuid,
  time_analysis jsonb,
  cheating_summary jsonb,
  personality_traits jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid,
  CONSTRAINT interview_results_pkey PRIMARY KEY (id),
  CONSTRAINT fk_interview_results_team_fit FOREIGN KEY (team_fit) REFERENCES public.teams(id),
  CONSTRAINT interview_results_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT interview_results_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.interview_assessments(id)
);
CREATE TABLE public.learning_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  doc_id uuid NOT NULL,
  storage_path text NOT NULL,
  file_size integer NOT NULL CHECK (file_size <= (5 * 1024 * 1024)),
  mime_type text NOT NULL,
  uploaded_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT learning_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT learning_attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id),
  CONSTRAINT learning_attachments_doc_id_fkey FOREIGN KEY (doc_id) REFERENCES public.learning_docs(id)
);
CREATE TABLE public.learning_docs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  folder_id uuid,
  title text NOT NULL,
  content text NOT NULL DEFAULT ''::text,
  created_by uuid NOT NULL,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  file_type text DEFAULT 'text'::text,
  deleted_by uuid,
  restored_at timestamp with time zone,
  restored_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT learning_docs_pkey PRIMARY KEY (id),
  CONSTRAINT learning_docs_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES public.learning_folders(id),
  CONSTRAINT learning_docs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT learning_docs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.learning_folders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  parent_id uuid,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  deleted_by uuid,
  restored_at timestamp with time zone,
  restored_by uuid,
  updated_by uuid,
  CONSTRAINT learning_folders_pkey PRIMARY KEY (id),
  CONSTRAINT learning_folders_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.learning_folders(id),
  CONSTRAINT learning_folders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.member_activity_daily (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  date date NOT NULL,
  task_updates_count integer DEFAULT 0,
  task_completes_count integer DEFAULT 0,
  comments_count integer DEFAULT 0,
  learning_events_count integer DEFAULT 0,
  meeting_joins_count integer DEFAULT 0,
  meeting_speaks_count integer DEFAULT 0,
  fitness_logs_count integer DEFAULT 0,
  other_events_count integer DEFAULT 0,
  raw_score integer DEFAULT 0,
  activity_score numeric DEFAULT 0,
  last_activity_at timestamp with time zone,
  inactive_days integer DEFAULT 0,
  status text DEFAULT 'inactive'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT member_activity_daily_pkey PRIMARY KEY (id),
  CONSTRAINT member_activity_daily_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.n_doc_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  folder_id uuid NOT NULL,
  name text NOT NULL,
  storage_path text NOT NULL,
  mime_type text,
  extension text,
  file_size bigint,
  owner_id uuid,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT n_doc_files_pkey PRIMARY KEY (id),
  CONSTRAINT n_doc_files_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES public.n_doc_folders(id),
  CONSTRAINT n_doc_files_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id),
  CONSTRAINT n_doc_files_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT n_doc_files_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT n_doc_files_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.n_doc_folders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  parent_id uuid,
  owner_id uuid,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT n_doc_folders_pkey PRIMARY KEY (id),
  CONSTRAINT n_doc_folders_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.n_doc_folders(id),
  CONSTRAINT n_doc_folders_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id),
  CONSTRAINT n_doc_folders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT n_doc_folders_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT n_doc_folders_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.ndoc_activity_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  activity_type USER-DEFINED NOT NULL,
  resource_id uuid NOT NULL,
  resource_type USER-DEFINED NOT NULL,
  resource_name character varying,
  details jsonb DEFAULT '{}'::jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ndoc_activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT ndoc_activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.ndoc_file_versions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  file_id uuid NOT NULL,
  version_number integer NOT NULL,
  storage_key character varying NOT NULL,
  storage_bucket character varying NOT NULL DEFAULT 'ndoc-files'::character varying,
  size bigint NOT NULL,
  mime_type character varying,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  change_notes text,
  CONSTRAINT ndoc_file_versions_pkey PRIMARY KEY (id),
  CONSTRAINT ndoc_file_versions_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.ndoc_files(id),
  CONSTRAINT ndoc_file_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.ndoc_files (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  original_name character varying NOT NULL,
  folder_id uuid,
  owner_id uuid NOT NULL,
  storage_key character varying NOT NULL,
  storage_bucket character varying NOT NULL DEFAULT 'ndoc-files'::character varying,
  mime_type character varying,
  size bigint NOT NULL,
  extension character varying,
  current_version integer DEFAULT 1,
  is_public boolean DEFAULT false,
  is_starred boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_accessed_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT ndoc_files_pkey PRIMARY KEY (id),
  CONSTRAINT ndoc_files_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES public.ndoc_folders(id),
  CONSTRAINT ndoc_files_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id)
);
CREATE TABLE public.ndoc_folders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  parent_id uuid,
  owner_id uuid NOT NULL,
  path text NOT NULL,
  is_root boolean DEFAULT false,
  color character varying,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT ndoc_folders_pkey PRIMARY KEY (id),
  CONSTRAINT ndoc_folders_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.ndoc_folders(id),
  CONSTRAINT ndoc_folders_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id)
);
CREATE TABLE public.ndoc_pending_uploads (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  storage_key text NOT NULL,
  file_name text NOT NULL,
  mime_type text,
  file_size bigint,
  folder_id uuid,
  url_expires_at timestamp with time zone NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'expired'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT ndoc_pending_uploads_pkey PRIMARY KEY (id),
  CONSTRAINT ndoc_pending_uploads_user_id_fkey1 FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.ndoc_recent_files (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  file_id uuid NOT NULL,
  accessed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ndoc_recent_files_pkey PRIMARY KEY (id),
  CONSTRAINT ndoc_recent_files_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT ndoc_recent_files_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.ndoc_files(id)
);
CREATE TABLE public.ndoc_resource_permissions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  resource_id uuid NOT NULL,
  resource_type USER-DEFINED NOT NULL,
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'viewer'::ndoc_permission_role,
  granted_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT ndoc_resource_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT ndoc_resource_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT ndoc_resource_permissions_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES public.users(id)
);
CREATE TABLE public.ndoc_starred_files (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  file_id uuid NOT NULL,
  starred_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ndoc_starred_files_pkey PRIMARY KEY (id),
  CONSTRAINT ndoc_starred_files_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT ndoc_starred_files_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.ndoc_files(id)
);
CREATE TABLE public.ndoc_trash (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  resource_id uuid NOT NULL,
  resource_type USER-DEFINED NOT NULL,
  resource_name character varying NOT NULL,
  original_path text,
  owner_id uuid NOT NULL,
  deleted_by uuid NOT NULL,
  deleted_at timestamp with time zone DEFAULT now(),
  auto_delete_at timestamp with time zone DEFAULT (now() + '30 days'::interval),
  original_data jsonb NOT NULL,
  CONSTRAINT ndoc_trash_pkey PRIMARY KEY (id),
  CONSTRAINT ndoc_trash_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id),
  CONSTRAINT ndoc_trash_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id)
);
CREATE TABLE public.ndoc_upload_sessions (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  upload_id character varying NOT NULL,
  storage_key character varying NOT NULL,
  file_name character varying NOT NULL,
  total_size bigint NOT NULL,
  chunk_size integer NOT NULL DEFAULT 5242880,
  uploaded_parts ARRAY DEFAULT ARRAY[]::integer[],
  folder_id uuid,
  mime_type character varying,
  status character varying NOT NULL DEFAULT 'in_progress'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT ndoc_upload_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT ndoc_upload_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT ndoc_upload_sessions_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES public.ndoc_folders(id)
);
CREATE TABLE public.notification_delivery_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL,
  attempt_number integer NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['success'::text, 'failed'::text])),
  provider_response jsonb,
  error_message text,
  duration_ms integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_delivery_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT notification_delivery_attempts_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.notification_jobs(id)
);
CREATE TABLE public.notification_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  notification_id uuid NOT NULL,
  channel text NOT NULL CHECK (channel = ANY (ARRAY['email'::text, 'telegram'::text, 'inapp'::text, 'slack'::text, 'discord'::text])),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  priority integer NOT NULL DEFAULT 5,
  attempts integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 3,
  next_run_at timestamp with time zone NOT NULL DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT notification_jobs_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES public.notifications_v2(id)
);
CREATE TABLE public.notification_provider_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_name text NOT NULL UNIQUE,
  channel text NOT NULL,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  enabled boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_provider_configs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notification_topics (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  default_channels ARRAY NOT NULL DEFAULT ARRAY['inapp'::text],
  enabled boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_topics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  event text NOT NULL,
  metadata jsonb NOT NULL,
  delivered boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.notifications_v2 (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipient_id uuid NOT NULL,
  topic_id text NOT NULL,
  actor_id uuid,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  idempotency_key text,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notifications_v2_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_v2_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.users(id),
  CONSTRAINT notifications_v2_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.notification_topics(id),
  CONSTRAINT notifications_v2_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id)
);
CREATE TABLE public.ntask_backgrounds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  storage_key text NOT NULL,
  file_name text NOT NULL,
  mime_type text NOT NULL,
  size bigint NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT ntask_backgrounds_pkey PRIMARY KEY (id),
  CONSTRAINT ntask_backgrounds_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.task_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  task_id uuid NOT NULL,
  actor_id uuid NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['create'::text, 'update'::text, 'move'::text, 'assign'::text, 'unassign'::text, 'complete'::text, 'attach'::text])),
  from_process text,
  to_process text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT task_activities_pkey PRIMARY KEY (id),
  CONSTRAINT task_activities_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT task_activities_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id)
);
CREATE TABLE public.task_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  task_id uuid NOT NULL,
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_size bigint NOT NULL DEFAULT 0,
  file_type text NOT NULL DEFAULT 'application/octet-stream'::text,
  uploaded_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT task_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT task_attachments_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT task_attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.task_comment_mentions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  task_comment_id uuid NOT NULL,
  mentioned_user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  restored_at timestamp with time zone,
  restored_by uuid,
  CONSTRAINT task_comment_mentions_pkey PRIMARY KEY (id),
  CONSTRAINT task_comment_mentions_task_comment_id_fkey FOREIGN KEY (task_comment_id) REFERENCES public.task_comments(id),
  CONSTRAINT task_comment_mentions_mentioned_user_id_fkey FOREIGN KEY (mentioned_user_id) REFERENCES public.users(id),
  CONSTRAINT task_comment_mentions_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT task_comment_mentions_restored_by_fkey FOREIGN KEY (restored_by) REFERENCES public.users(id)
);
CREATE TABLE public.task_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  task_id uuid NOT NULL,
  author_id uuid NOT NULL,
  comment text NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  restored_at timestamp with time zone,
  restored_by uuid,
  CONSTRAINT task_comments_pkey PRIMARY KEY (id),
  CONSTRAINT task_comments_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT task_comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id),
  CONSTRAINT task_comments_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT task_comments_restored_by_fkey FOREIGN KEY (restored_by) REFERENCES public.users(id)
);
CREATE TABLE public.task_shares (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  task_id uuid NOT NULL,
  member_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  shared_by uuid,
  CONSTRAINT task_shares_pkey PRIMARY KEY (id),
  CONSTRAINT task_shares_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT task_shares_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.users(id)
);
CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_by uuid NOT NULL,
  work_id uuid NOT NULL,
  title text NOT NULL,
  process text NOT NULL DEFAULT 'Resources'::text CHECK (process = ANY (ARRAY['Resources'::text, 'Idea'::text, 'Todo'::text, 'Doing'::text, 'Done'::text, 'Performance'::text, 'Released'::text])),
  description text,
  start_date timestamp with time zone,
  due_date timestamp with time zone,
  position text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  label jsonb,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  delete_reason text,
  restored_at timestamp with time zone,
  restored_by uuid,
  labels ARRAY DEFAULT '{}'::uuid[],
  cover jsonb,
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT tasks_work_id_fkey FOREIGN KEY (work_id) REFERENCES public.works(id),
  CONSTRAINT tasks_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT tasks_restored_by_fkey FOREIGN KEY (restored_by) REFERENCES public.users(id)
);
CREATE TABLE public.team_energy_daily (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL,
  date date NOT NULL,
  task_updates_count integer NOT NULL DEFAULT 0,
  task_completes_count integer NOT NULL DEFAULT 0,
  comments_count integer NOT NULL DEFAULT 0,
  learning_events_count integer NOT NULL DEFAULT 0,
  meeting_joins_count integer NOT NULL DEFAULT 0,
  meeting_speaks_count integer NOT NULL DEFAULT 0,
  fitness_logs_count integer NOT NULL DEFAULT 0,
  other_events_count integer NOT NULL DEFAULT 0,
  raw_score integer NOT NULL DEFAULT 0,
  energy_score numeric NOT NULL DEFAULT 0,
  consistency_bonus numeric NOT NULL DEFAULT 0,
  final_score numeric NOT NULL DEFAULT 0,
  active_members_count integer NOT NULL DEFAULT 0,
  total_members_count integer NOT NULL DEFAULT 0,
  avg_score_last_7_days numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT team_energy_daily_pkey PRIMARY KEY (id),
  CONSTRAINT team_energy_daily_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.teams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  deleted_by uuid,
  restored_at timestamp with time zone,
  restored_by uuid,
  description text,
  updated_by uuid,
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT teams_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.time_off_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  requester_id uuid NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'PENDING'::text CHECK (status = ANY (ARRAY['PENDING'::text, 'APPROVED'::text, 'REJECTED'::text, 'CANCELLED'::text])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT time_off_requests_pkey PRIMARY KEY (id),
  CONSTRAINT time_off_requests_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES public.users(id),
  CONSTRAINT time_off_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.tracking_telegram_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  message_identity_id uuid,
  chat_id bigint NOT NULL,
  message_id bigint NOT NULL,
  telegram_user_id bigint,
  message_type text,
  caption text,
  file_id text NOT NULL,
  file_unique_id text,
  file_name text,
  mime_type text,
  file_size bigint,
  width integer,
  height integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tracking_telegram_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT tracking_telegram_attachments_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.tracking_telegram_message_events(id),
  CONSTRAINT tracking_telegram_attachments_message_identity_id_fkey FOREIGN KEY (message_identity_id) REFERENCES public.tracking_telegram_message_identities(id)
);
CREATE TABLE public.tracking_telegram_message_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  message_identity_id uuid,
  event_kind USER-DEFINED NOT NULL,
  chat_id bigint NOT NULL,
  message_id bigint NOT NULL,
  telegram_user_id bigint,
  username text,
  full_name text,
  chat_type text,
  chat_title text,
  message_text text,
  message_type text,
  reply_to_message_id bigint,
  forwarded_from_user_id bigint,
  sent_at timestamp with time zone,
  edited_at timestamp with time zone,
  event_ts timestamp with time zone,
  raw_json jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tracking_telegram_message_events_pkey PRIMARY KEY (id),
  CONSTRAINT tracking_telegram_message_events_message_identity_id_fkey FOREIGN KEY (message_identity_id) REFERENCES public.tracking_telegram_message_identities(id)
);
CREATE TABLE public.tracking_telegram_message_identities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  chat_id bigint NOT NULL,
  message_id bigint NOT NULL,
  telegram_user_id bigint,
  username text,
  full_name text,
  chat_type text,
  chat_title text,
  reply_to_message_id bigint,
  forwarded_from_user_id bigint,
  first_sent_at timestamp with time zone,
  latest_sent_at timestamp with time zone,
  latest_edited_at timestamp with time zone,
  last_activity_at timestamp with time zone,
  latest_text text,
  latest_type text,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  latest_event_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tracking_telegram_message_identities_pkey PRIMARY KEY (id)
);
CREATE TABLE public.training_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  training_video_id uuid,
  name text NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  created_by uuid,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  restored_at timestamp with time zone,
  restored_by uuid,
  CONSTRAINT training_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT training_assignments_training_video_id_fkey FOREIGN KEY (training_video_id) REFERENCES public.training_videos(id),
  CONSTRAINT training_assignments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT training_assignments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT training_assignments_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT training_assignments_restored_by_fkey FOREIGN KEY (restored_by) REFERENCES public.users(id)
);
CREATE TABLE public.training_playlist_videos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  training_playlist_id uuid,
  training_video_id uuid,
  position text DEFAULT 'h'::text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  created_by uuid,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  restored_at timestamp with time zone,
  restored_by uuid,
  CONSTRAINT training_playlist_videos_pkey PRIMARY KEY (id),
  CONSTRAINT training_playlist_videos_training_playlist_id_fkey FOREIGN KEY (training_playlist_id) REFERENCES public.training_playlists(id),
  CONSTRAINT training_playlist_videos_training_video_id_fkey FOREIGN KEY (training_video_id) REFERENCES public.training_videos(id),
  CONSTRAINT training_playlist_videos_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT training_playlist_videos_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT training_playlist_videos_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT training_playlist_videos_restored_by_fkey FOREIGN KEY (restored_by) REFERENCES public.users(id)
);
CREATE TABLE public.training_playlists (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid,
  title text NOT NULL,
  thumbnail_url text,
  description text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  created_by uuid,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  restored_at timestamp with time zone,
  restored_by uuid,
  CONSTRAINT training_playlists_pkey PRIMARY KEY (id),
  CONSTRAINT training_playlists_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT training_playlists_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT training_playlists_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT training_playlists_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT training_playlists_restored_by_fkey FOREIGN KEY (restored_by) REFERENCES public.users(id)
);
CREATE TABLE public.training_quizzes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  training_video_id uuid,
  question text NOT NULL,
  answers ARRAY NOT NULL,
  correct_answer integer NOT NULL,
  explanation text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  created_by uuid,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  restored_at timestamp with time zone,
  restored_by uuid,
  CONSTRAINT training_quizzes_pkey PRIMARY KEY (id),
  CONSTRAINT training_quizzes_training_video_id_fkey FOREIGN KEY (training_video_id) REFERENCES public.training_videos(id),
  CONSTRAINT training_quizzes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT training_quizzes_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT training_quizzes_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT training_quizzes_restored_by_fkey FOREIGN KEY (restored_by) REFERENCES public.users(id)
);
CREATE TABLE public.training_user_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assignment_id uuid NOT NULL,
  user_id uuid NOT NULL,
  content text,
  updated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT training_user_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT training_user_assignments_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.training_assignments(id),
  CONSTRAINT training_user_assignments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.training_user_quizzes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  training_video_id uuid,
  training_quiz_id uuid,
  user_id uuid,
  answer integer NOT NULL,
  is_correct boolean NOT NULL,
  time_taken integer NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  created_by uuid,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  restored_at timestamp with time zone,
  restored_by uuid,
  CONSTRAINT training_user_quizzes_pkey PRIMARY KEY (id),
  CONSTRAINT training_user_quizzes_training_video_id_fkey FOREIGN KEY (training_video_id) REFERENCES public.training_videos(id),
  CONSTRAINT training_user_quizzes_training_quiz_id_fkey FOREIGN KEY (training_quiz_id) REFERENCES public.training_quizzes(id),
  CONSTRAINT training_user_quizzes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT training_user_quizzes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT training_user_quizzes_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT training_user_quizzes_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT training_user_quizzes_restored_by_fkey FOREIGN KEY (restored_by) REFERENCES public.users(id)
);
CREATE TABLE public.training_user_video_process (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  training_video_id uuid NOT NULL,
  completed_at timestamp with time zone,
  current_time_watched integer DEFAULT 0,
  max_time_watched integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT training_user_video_process_pkey PRIMARY KEY (id),
  CONSTRAINT training_user_video_process_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT training_user_video_process_training_video_id_fkey FOREIGN KEY (training_video_id) REFERENCES public.training_videos(id)
);
CREATE TABLE public.training_videos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  video_url text NOT NULL,
  thumbnail_url text,
  duration_seconds integer,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  created_by uuid,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  restored_at timestamp with time zone,
  restored_by uuid,
  CONSTRAINT training_videos_pkey PRIMARY KEY (id),
  CONSTRAINT training_videos_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT training_videos_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT training_videos_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT training_videos_restored_by_fkey FOREIGN KEY (restored_by) REFERENCES public.users(id)
);
CREATE TABLE public.user_google_credentials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid DEFAULT gen_random_uuid(),
  google_user_id text,
  email text,
  access_token text,
  refresh_token text,
  expires_at text,
  scope text,
  token_type text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_google_credentials_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_notification_prefs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  topic_id text NOT NULL,
  channels ARRAY NOT NULL DEFAULT ARRAY['inapp'::text],
  enabled boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_notification_prefs_pkey PRIMARY KEY (id),
  CONSTRAINT user_notification_prefs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_notification_prefs_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.notification_topics(id)
);
CREATE TABLE public.user_teams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  team_id uuid,
  team_role USER-DEFINED NOT NULL DEFAULT 'trainee'::team_role,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  deleted_at timestamp without time zone,
  deleted_by uuid,
  restored_at timestamp with time zone,
  restored_by uuid,
  CONSTRAINT user_teams_pkey PRIMARY KEY (id),
  CONSTRAINT user_teams_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_teams_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT user_teams_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT user_teams_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT user_teams_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT user_teams_restored_by_fkey FOREIGN KEY (restored_by) REFERENCES public.users(id)
);
CREATE TABLE public.user_zoom_credentials (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  zoom_account_id text NOT NULL,
  zoom_client_id text NOT NULL,
  zoom_client_secret_encrypted text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_zoom_credentials_pkey PRIMARY KEY (id),
  CONSTRAINT user_zoom_credentials_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auth_id uuid NOT NULL,
  email text NOT NULL,
  full_name text,
  role text DEFAULT 'member'::text CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'manager'::text, 'member'::text, 'candidate'::text])),
  avatar_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  address text,
  cccd text,
  dob date,
  gender text CHECK (gender = ANY (ARRAY['male'::text, 'female'::text, 'other'::text])),
  nid text,
  phone text,
  nickname text,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  telegram_user_id bigint UNIQUE,
  zoom_account_id text,
  zoom_client_id text,
  zoom_client_secret text,
  band text,
  education text,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_auth_id_fkey FOREIGN KEY (auth_id) REFERENCES auth.users(id)
);
CREATE TABLE public.version_updates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  module text NOT NULL,
  user_id uuid,
  telegram_user_id bigint NOT NULL,
  telegram_message_id bigint NOT NULL,
  features jsonb NOT NULL,
  raw_message text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT version_updates_pkey PRIMARY KEY (id),
  CONSTRAINT version_updates_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.work_invite_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  work_id uuid NOT NULL,
  created_by uuid NOT NULL,
  token text NOT NULL UNIQUE,
  require_approval boolean NOT NULL DEFAULT false,
  default_role text NOT NULL CHECK (default_role = ANY (ARRAY['member'::text, 'admin'::text, 'owner'::text])),
  max_uses integer,
  used_count integer NOT NULL DEFAULT 0,
  expire_at timestamp with time zone,
  status text NOT NULL DEFAULT 'ACTIVE'::text CHECK (status = ANY (ARRAY['ACTIVE'::text, 'PAUSED'::text, 'REVOKED'::text])),
  allowed_email_domain ARRAY,
  note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT work_invite_links_pkey PRIMARY KEY (id),
  CONSTRAINT work_invite_links_work_id_fkey FOREIGN KEY (work_id) REFERENCES public.works(id),
  CONSTRAINT work_invite_links_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.work_join_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  work_id uuid NOT NULL,
  invite_link_id uuid,
  requester_id uuid NOT NULL,
  message text,
  status text NOT NULL DEFAULT 'PENDING'::text CHECK (status = ANY (ARRAY['PENDING'::text, 'APPROVED'::text, 'REJECTED'::text, 'CANCELLED'::text])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT work_join_requests_pkey PRIMARY KEY (id),
  CONSTRAINT work_join_requests_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES public.users(id),
  CONSTRAINT work_join_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id),
  CONSTRAINT work_join_requests_work_id_fkey FOREIGN KEY (work_id) REFERENCES public.works(id),
  CONSTRAINT work_join_requests_invite_link_id_fkey FOREIGN KEY (invite_link_id) REFERENCES public.work_invite_links(id)
);
CREATE TABLE public.work_shares (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  work_id uuid NOT NULL,
  shared_by uuid NOT NULL,
  member_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'member'::text CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT work_shares_pkey PRIMARY KEY (id),
  CONSTRAINT work_shares_work_id_fkey FOREIGN KEY (work_id) REFERENCES public.works(id),
  CONSTRAINT work_shares_shared_by_fkey FOREIGN KEY (shared_by) REFERENCES public.users(id),
  CONSTRAINT work_shares_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.users(id)
);
CREATE TABLE public.work_task_labels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  label_name text NOT NULL,
  label_color character varying NOT NULL CHECK (label_color::text ~* '^#[0-9A-F]{6}$'::text),
  work_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT work_task_labels_pkey PRIMARY KEY (id),
  CONSTRAINT work_task_labels_work_id_fkey FOREIGN KEY (work_id) REFERENCES public.works(id)
);
CREATE TABLE public.works (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_by uuid NOT NULL,
  name text NOT NULL,
  description text,
  background text NOT NULL,
  background_type text DEFAULT 'image'::text CHECK (background_type = ANY (ARRAY['image'::text, 'color'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  deleted_by uuid,
  delete_reason text,
  restored_at timestamp with time zone,
  restored_by uuid,
  CONSTRAINT works_pkey PRIMARY KEY (id),
  CONSTRAINT works_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT works_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT works_restored_by_fkey FOREIGN KEY (restored_by) REFERENCES public.users(id)
);